apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-embedding-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: embedding-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080