apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rerank-api
  labels:
    app: rerank-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rerank-api
  template:
    metadata:
      labels:
        app: rerank-api
    spec:
      containers:
        - name: rerank-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8888  
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          